name: Generate and save dependency graph

on:
  pull_request:

permissions: {}

env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17

      - name: Generate and save dependency graph
        uses: gradle/actions/dependency-submission@v6
        with:
          dependency-graph: generate-and-upload
